services:
  mariadb:
    image: mariadb:11.8.5
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: HarvestArea
      MARIADB_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql:rw
    networks:
      - app_network

  mongodb:
    image: mongo:8.0.18
    restart: unless-stopped
    environment:
      - MONGODB_INITDB_DATABASE=HarvestArea
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db:rw
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - app_network

volumes:
  db_data_dev:
  mongo_data_dev:

networks:
  app_network: